projects:
  - num: 1
    basename: image-proj
    tuning: default
    templates:
      - num: 50000
        file: ./content/image-template.json
quotas:
  - name: default
    file: default

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 10 s
      rate_limit:
        delay: 250 ms
